# Generated by Django 5.1.15 on 2026-05-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payment_reminder_flag'),
        ('core', '0010_airport_transfer'),
    ]

    operations = [
    ]
