# Generated by Django 5.1.15 on 2026-07-31 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_paypal_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafariPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "3-Day Maasai Mara Classic"', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('duration_days', models.PositiveSmallIntegerField(default=1, help_text='Total trip length in days.')),
                ('summary', models.CharField(blank=True, help_text='1-2 sentence hook shown on package listings.', max_length=300)),
                ('itinerary', models.TextField(blank=True, help_text='Day-by-day itinerary, freeform.')),
                ('includes', models.TextField(blank=True, help_text="What's included in the price.")),
                ('excludes', models.TextField(blank=True, help_text="What's NOT included — state accommodation here if it's excluded.")),
                ('image', models.ImageField(blank=True, null=True, upload_to='safari/packages/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from listings without deleting.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SafariPackagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=2, help_text='Total price for this vehicle on this package, USD.', max_digits=8)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.safaripackage')),
                ('vehicle', models.ForeignKey(limit_choices_to={'category': 'safari'}, on_delete=django.db.models.deletion.CASCADE, related_name='safari_package_prices', to='core.vehicle')),
            ],
            options={
                'verbose_name': 'Safari package price',
                'verbose_name_plural': 'Safari package pricing',
                'ordering': ['package__order', 'vehicle__order'],
                'unique_together': {('package', 'vehicle')},
            },
        ),
    ]
