# Generated by Django 5.2.17 on 2026-08-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_safari_packages'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(
                condition=models.Q(('payment_status', 'paid'), models.Q(('payment_ref', ''), _negated=True)),
                fields=('payment_ref',),
                name='unique_payment_ref_when_paid',
            ),
        ),
    ]
